name: 🥯 Bitzy on Buns
description: "Release a Bitey package automatically."
author: "Chocobitey"


icon: arrow-up-circle
color: blue

inputs:
  name:
    description: "The name of the package"
    required: true
  version:
    description: "The version to release"
    required: true

runs:
  using: "composite"
  steps:
    - name: 🧾 Checkout source
      uses: actions/checkout@v3

    - name: 📦 Create .choco.pkg
      shell: bash
      run: |
        mkdir -p release
        tar -czf "release/${{ inputs.name }}-${{ inputs.version }}.choco.pkg" *

    - name: 📤 Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: choco-pkg
        path: release/${{ inputs.name }}-${{ inputs.version }}.choco.pkg

    - name: 🧾 Download build artifact (again for release)
      uses: actions/download-artifact@v4
      with:
        name: choco-pkg
        path: release

    - name: 📤 Upload Package to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/${{ inputs.name }}-${{ inputs.version }}.choco.pkg
